apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: scmddd688-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: scmddd688-nodejs 
  name: scmddd688-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: scmddd688-nodejs 
